apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress
spec:
  type: NodePort
  ports:
   - protocol: TCP
     targetPort: 80
     port: 80
     nodePort: 30009
  selector:
    app: wordpress

