apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql
  namespace: wordpress
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db-data"
