apiVersion: v1
kind: Pod
metadata:
  name: pg-color-2
  namespace: production
  labels:
     app: web
     role: webapp
spec:
  containers:
    - name: webapp
      image: kodekloud/webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: blue
